"""create tables

Revision ID: 8663821ee15b
Revises: 
Create Date: 2026-07-15 14:04:17.762710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8663821ee15b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('account_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('Collector', 'Supervisor', 'Admin', name='memberrole'), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('profile_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('account_email')
    )
    op.create_table('dataset',
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('command', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dataset_type', sa.Enum('Training', 'Validation', 'Testing', name='datasettype'), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('dataset_id')
    )
    op.create_table('intent',
    sa.Column('intent_id', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['account.account_id'], ),
    sa.PrimaryKeyConstraint('intent_id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('ner',
    sa.Column('ner_id', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['account.account_id'], ),
    sa.PrimaryKeyConstraint('ner_id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('datasetintent',
    sa.Column('intent_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('start_index', sa.Integer(), nullable=False),
    sa.Column('end_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.dataset_id'], name='datasetintent_dataset', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['intent_id'], ['intent.intent_id'], ),
    sa.PrimaryKeyConstraint('intent_id', 'dataset_id')
    )
    op.create_table('nerintentlink',
    sa.Column('ner_id', sa.Integer(), nullable=False),
    sa.Column('intent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['intent_id'], ['intent.intent_id'], ),
    sa.ForeignKeyConstraint(['ner_id'], ['ner.ner_id'], ),
    sa.PrimaryKeyConstraint('ner_id', 'intent_id')
    )
    op.create_table('datasetintentner',
    sa.Column('ner_id', sa.Integer(), nullable=False),
    sa.Column('intent_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('start_index', sa.Integer(), nullable=False),
    sa.Column('end_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['intent_id', 'dataset_id'], ['datasetintent.intent_id', 'datasetintent.dataset_id'], name='fk_datasetintentner_datasetintent_dataset', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ner_id'], ['ner.ner_id'], ),
    sa.PrimaryKeyConstraint('ner_id', 'intent_id', 'dataset_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datasetintentner')
    op.drop_table('nerintentlink')
    op.drop_table('datasetintent')
    op.drop_table('ner')
    op.drop_table('intent')
    op.drop_table('dataset')
    op.drop_table('account')
    # ### end Alembic commands ###
