"""add realtionship mapping to meta models

Revision ID: c9fe5fefe553
Revises: 8663821ee15b
Create Date: 2026-07-15 16:52:16.830823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9fe5fefe553'
down_revision: Union[str, Sequence[str], None] = '8663821ee15b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_dataset_member', 'account', ['member_id'], ['account_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.drop_constraint('fk_dataset_member', type_='foreignkey')

    # ### end Alembic commands ###
