"""add description to intent

Revision ID: d58708129679
Revises: c9fe5fefe553
Create Date: 2026-07-15 23:11:17.875965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd58708129679'
down_revision: Union[str, Sequence[str], None] = 'c9fe5fefe553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intent', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
